run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gosec
    - prealloc
    - unconvert
    - unparam
    - whitespace

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/hbttundar/scg-support
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
  gosec:
    excludes:
      - G104 # Disable "Errors unhandled" as it's already covered by errcheck
      - G115 # Disable "Integer overflow" warning for uint64 conversions

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - unparam
